spring:
  application:
    name: im-sql-save


server:
  port: 10319

eureka:
  client:
    service-url:
      defaultZone: http://quyuanjin:614854010@120.79.178.226:10311/eureka/
  instance:
    prefer-ip-address: true
