spring:
  application:
    name: im-api-login


server:
  port: 10316

eureka:
  client:
    service-url:
      defaultZone: http://quyuanjin:614854010@120.79.178.226:10311/eureka/
  instance:
    prefer-ip-address: true
